// <auto-generated />
namespace TimeTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PersonType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonType));
        
        string IMigrationMetadata.Id
        {
            get { return "201212310743014_PersonType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
